name: CAPE
on:
    push:
        branches: [main]
    pull_request:

permissions:
    pages: write
    id-token: write

jobs:
    python:
        name: Python
        uses: cape-ph/.github/.github/workflows/poetry_python_checks.yml@sphinx
        with:
            pytest: true
            sphinx: true
    general:
        name: General
        uses: cape-ph/.github/.github/workflows/general_checks.yml@v1
