name: Documentation
on:
    push:
        branches: [main]
    pull_request:

permissions:
    pages: write
    id-token: write

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              id: setup_python
              with:
                  python-version: 3.11
            - uses: abatilo/actions-poetry@v2
            - name: install dependencies
              run: poetry install
            - name: build documentation
              run: |
                  cd docs
                  make html
            - name: upload documentation artifacts
              id: deployment
              uses: actions/upload-pages-artifact@v3
              with:
                  path: docs/_build/html/
    deploy:
        name: Deploy
        if: ${{ github.event_name == 'push' }}
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/deploy-pages@v4
              id: deployment
